#ifndef ENUMS_H
#define ENUMS_H

enum TOOL {PENCIL, ERASER, CIRCLE, TRIANGLE, RECTANGLE, POLYGON, MOUSE};

enum COLOR {RED, ORANGE, YELLOW, GREEN, BLUE, VIOLET, WHITE, BLACK, CUSTOM};

enum ACTION {NONE, UNDO, CLEAR};

#endif